[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyzx48tools"
version = "0.1.0"
dependencies = [
    "pillow",
    "pyzipper"
]
requires-python = ">=3.6"
